require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

AllCops:
  Exclude:
    - vendor/**/*
    - templates/**/*

Jekyll/NoPutsAllowed:
  Enabled: false
