# This file is auto-generated by Jekyll Auth
# Feel free to add additional Rake tasks so long as
# `rake assets:precompile` continues to generate the jekyll site

task :default => :install

task :install do
  require 'mkmf'
  puts "TEST"
  `wget -qO- https://toolbelt.heroku.com/install.sh | sh` if find_executable("heroku2").nil?
end

namespace :assets do
  task :precompile do
    sh "bundle exec jekyll-auth build"
  end
end
